### ISSUE TITLE
Global validation of rewriting output

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#128]
After a `tryRule`, each output graph should be saved independently.

It would be helpful to have a way to select a subpart or to select all graphs and save them in one operation

**Comment by Ingerid** [comment]
Hi, I'd like to chime in and request that this functionality is prioritised.  

At the Norwegian Language Bank (the National Library of Norway) we are currently working on a new conversion of the [Norwegian dependency treebank](https://www.nb.no/sprakbanken/en/resource-catalogue/oai-nb-no-sbr-10/) to the UD format with the latest guidelines for v2.10, and are looking into using Grew and Arborator Grew in that process. The rule development and validation of resulting graphs would both be greatly accelerated if it was possible to save all graph results with a single button, instead of clicking through each sentence individually.

**Comment by RZiane** [comment]
We would like to use this function to lemmatize our corpus on the interface. It would be great if this was implemented.

**Comment by kirianguiller** [comment]
Yes, thanks for your message. We already thought about adding this in the past. When I will have some time soon, I will check what need to be done for this and make a plan first, and let you know.

**Comment by khansadaoudi** [comment]
added in this commit [9170829](https://github.com/Arborator/arborator-frontend/commit/91708291269320a8730f5f5c00cf1dbc2ac5f8af)
