### ISSUE TITLE
Limitation in the number of MISC features

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#129]
The number of MISC features that are viewed and edited in Arborator ils limited to 5. If there are more, they cannot be viewed; if there are 5 shown already, you cannot add new ones. This is a severe handicap!

**Comment by bguil** [comment]
It seems to be a display problem. The add button creates new features but they are not shown.

I suspect a limitation to a display of 5 features due to pagination. 
The code line below is supposed to remove this limitation, but it is not taken into account, I don't know why...

https://github.com/Arborator/arborator-frontend/blob/821c2d113a297a6152581ecd032e38b7fad6a2eb/src/components/sentence/AttributeTable.vue#L116

@gguibon, @kimgerdes, @kirianguiller: any idea on how to fix this?

**Comment by B-CARON** [comment]
This is probably linked to another problem : it is not possible in Aborator to create new features when 5 are already displayed.   Bernard Caron57, avenue d’Italie75013 PARIS06 63 68 15 19 De : Bruno GuillaumeEnvoyé le :jeudi 11 août 2022 09:14À : Arborator/arborator-frontendCc : B-CARON; AuthorObjet :Re: [Arborator/arborator-frontend] Limitation in the number of MISC features (Issue #129) It seems to be a display problem. The add button creates new features but they are not shown.I suspect a limitation to a display of 5 features due to pagination.The code line below is supposed to remove this limitation, but it is not taken into account, I don't know ***@***.***, @kimgerdes, @kirianguiller: any idea on how to fix this?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by kirianguiller** [comment]
Thanks all. @gguibon , it was indeed a pagination problem. Removing "hide-bottom" from q-table component fixed the issue (this line : https://github.com/Arborator/arborator-frontend/commit/1837e8bd2cfcb6e082357cb0d799a82f8583e971#diff-d70aa00bc145e09fe87a18539e51d14e9f3788d74c0080c1a548548141d079d4L6)

Closing the issue
