### ISSUE TITLE
Push and replace trees

### ISSUE THREAD

**Issue by perrier54** [Arborator/arborator-frontend#14]
The two buttons in the project menu that allow us to push and replace trees are not understandable:
1. What is the distinction between my trees and all trees ? Does it mean that we can act on the trees of the other users ?
2. What is the difference between push only my trees of the selected examples and push my trees of the selected examples, filled up with the most recent trees ? What else can we do but push the examples filled up with the most recent trees?
3. Regarding tree replacement, what are the trees from the GitHub? What is the relationship between Arborator and GitHub?

**Comment by marinecourtin** [comment]
First I should preface by saying that all of these functionalities are only available if :
- the user is loggged in with their github account
- they have granted the required permissions to the github app arborator-grew :
> 1. Create a repository on your github account (this will act as your storage base).<br>
> 2. Go to https://github.com/apps/arborator-grew/ and click Install<br>
> 3. Look over the granted permissions and if you accept select 1 repository (created at step 1.) and click Install & Authorize.


___________________

1. my trees : all trees that have been created by the user marinecourtin logged in with github. There is a possibility (reserved only to the admin of the project) to act on the trees of others. **Normal users can only update their own trees**.

1. We have updated the buttons (they were confusing), now the available options for pushing are:
- user : only push the trees that were created by the current user, so if the user has no tree for a sentence the sentence will not appear in the pushed data.
- user then recent : for each sentence, if the user has a tree, push it, otherwise push the tree that was last modified.
- recent (admin only) : push the tree that was last modified, regardless of the user.
- all (admin only) : for every user, push their trees (this will create a file per user)

![Capture d’écran de 2020-06-17 15-24-31](https://user-images.githubusercontent.com/28790155/84903865-e91cd380-b0ae-11ea-82ca-d91c25254feb.png)



3. trees can be replaced with trees that are found on the github storage of the user (either they were pushed using arboratorgrew or they were manually added by the user). This can be especially useful is you have applied grew rewriting rules on some trees and you wish to update them or revert to a previous version because the rules had some undesirable effect.
- user : replace your trees on arboratorgrew with your trees stored on github
- all (admin) : for every user replace their trees with the ones stored on github

![Capture d’écran de 2020-06-17 15-24-40](https://user-images.githubusercontent.com/28790155/84903876-ecb05a80-b0ae-11ea-85e4-1ec45081afc6.png)



And on my github account, the stored trees would look something like this : 
![Capture d’écran de 2020-06-17 15-23-04](https://user-images.githubusercontent.com/28790155/84903582-904d3b00-b0ae-11ea-9df1-14e66e14514e.png)
![Capture d’écran de 2020-06-17 15-23-11](https://user-images.githubusercontent.com/28790155/84903594-93482b80-b0ae-11ea-9d7c-f77e9e46e977.png)


Hope that clarifies everything !
