### ISSUE TITLE
Parser issue: timeout

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#181]
Tried to use the parser on the Zaar corpus. Selected 3 files to train on (CONV 1 to 3), then the 5 remaining files to parse. Launched the app. It started working but I soon got a timeout message. 
Where did I go wrong? 

@kimgerdes @bguil @kirianguiller

**Comment by kirianguiller** [comment]
@kimgerdes , @ziqianPeng , we need to make a meeting on the parsing, to fix this

**Comment by ziqianPeng** [comment]
Hello! 

As I know, we changed the location of the hardware, and we had to set up again the configuration to receive requests from outside of the machine. 
If the request couldn't arrive at the backend, it will give the time-out error as described in Issue #181. 
[ https://github.com/kimgerdes | @kimgerdes ] maybe the issue is not fixed yet? 

It's true that the logging functions are not well set and it shows 'bootstrap parsing...' by default. 
The real first log from the backend should be kind of 'preparing dataset'. I put the default message 'bootstrap parsing...' because the frontend begins to ask for the logs from progress.txt before the backend begins to write the first log, maybe because the function is asynchronous. 

After that it's true we should meet to update the bootparser. 

Best Regards 

Ziqian Peng 



De: "Kirian Guiller" ***@***.***> 
À: "Arborator/arborator-frontend" ***@***.***> 
Cc: "Ziqian Peng" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Lundi 16 Janvier 2023 18:06:26 
Objet: Re: [Arborator/arborator-frontend] Parser issue: timeout (Issue #181) 





[ https://github.com/kimgerdes | @kimgerdes ] , [ https://github.com/ziqianPeng | @ziqianPeng ] , we need to make a meeting on the parsing, to fix this

**Comment by kirianguiller** [comment]
@B-CARON , the parsing machine is now online. Can you try again to parse your corpus ? It should works normally now

**Comment by B-CARON** [comment]
Bonjour Kirian J’ai réussi à utiliser le parseur Kir. Transkit a planté. Vous voulez que j’essaie les autres ?  Merci beaucoup Bernard Bernard Caron57, avenue d’Italie75013 PARIS06 63 68 15 19 De : Kirian GuillerEnvoyé le :lundi 23 janvier 2023 17:51À : Arborator/arborator-frontendCc : B-CARON; MentionObjet :Re: [Arborator/arborator-frontend] Parser issue: timeout (Issue ***@***.*** , the parsing machine is now online. Can you try again to parse your corpus ? It should works normally now—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by kirianguiller** [comment]
Yes, could you try with the other parser please ? And if it doesn't work, could you please send a screenshot of the config and the name of the project/sample  ?
Thanks !

**Comment by B-CARON** [comment]
I tested all the Tools. Only 2 worked. As I don’t understand the reports (jsons), your comments would help. Name of Project : Zaar_Parsing_Tests. I created the project fot your own use. My own working project is different. NB : the popup messages  in Arborator only stay visible for a few seconds. It’s hardly possible to read them. Could they stay a bit longer so we can read  them properly, and take steps to correct our mistakes ?  Transkit : Training failed. See screenprint below.   Kir : Succeeded with same project and configuration. See attached report.  Hops : Same project and configuration. The training failed. No report. Same popup.  Udify : Failed at parsing stage. No report. Same popup. Stanza : Succeeded with same project and configuration. See attached report.   Hope this helps.  B.   Bernard Caron57, avenue d’Italie75013 PARIS06 63 68 15 19 De : Kirian GuillerEnvoyé le :mardi 24 janvier 2023 17:54À : Arborator/arborator-frontendCc : B-CARON; MentionObjet :Re: [Arborator/arborator-frontend] Parser issue: timeout (Issue #181) Yes, could you try with the other parser please ? And if it doesn't work, could you please send a screenshot of the config and the name of the project/sample ?Thanks !—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ziqianPeng** [comment]
Hello,

Thanks a lot for your feedback!
```
It seems that the message begins with
"<!--
/* Font Definitions */
@font-face
{font-family:"Cambria Math";
"
```

is not a bug report, can we know where you copied that? 

After checking the log file of parser backend, it seems that trankit is failed to train tokenizer required in its pipeline, we didn't know the reason yet and we'll look at it further...

hopsparser and udify succeeded in training a model but failed to parse. 
For hopsparser, it seems that it makes use of the HEAD and DEPREL columns in files to parse, and it throws UDError if there's no root. Can you give a root to the sentences: 
`# sent_id = SAY_BC_INT_01_Religion_286-286` and `# sent_id = SAY_BC_INT_01_Religion_239-241`
 in `SAY_NC_INT_01_religion.conllu`, then train with the 3 gold files and parse only this file after modification? I hope this works. We'll update the djangoBootparser to fix this problem soon.

Udify threw another error during parsing we are trying to fix it.

We'll try to make the popup message appears longer. In some cases, for example, if there's no unique root or there's underscore in HEAD in files to train (that didn't occur in the 3 training files of Zaar_Parsing_Tests), you may get a (currently very draft) error report and the relevant conll sentences will be removed. 

Thanks!

**Comment by kirianguiller** [comment]
Hello @B-CARON . We improved and made more stable the pipeline (especially for the kirparser). We now have no problem parsing your corpus (CONV-1 to 3 for training and the rest for parsing). I've just run a parsing with 30 epochs (less than 10mn) and I got the following results : 
```json
{"UPOS":{"precision":0.9035667107001321,"recall":0.9035667107001321,"f1":0.9035667107001321},
"XPOS":{"precision":1,"recall":1,"f1":1},
"UFeats":{"precision":0.8665785997357992,"recall":0.8665785997357992,"f1":0.8665785997357992},
"Lemmas":{"precision":0.8705416116248349,"recall":0.8705416116248349,"f1":0.8705416116248349},
"UAS":{"precision":0.7582562747688243,"recall":0.7582562747688243,"f1":0.7582562747688243},
"LAS":{"precision":0.6842800528401585,"recall":0.6842800528401585,"f1":0.6842800528401585}}
```

I'm running another one with many more epochs to see how much we can reach for LAS.

**Comment by B-CARON** [comment]
Hi @Kirian I had no problem using the kirparser. It has always worked for me. I have run your latest version, but from my point of view, the latest version is not dramatically better for punctuation…  I have another problem though : the parser plays havoc with the lemmas. It introduces new lemmas which are faulty. It seems to be troubled by diacritics. This may be due to a divergence between the way Bruno (=the UD website) treats them : whenever they exist, be website uses single signs where we (Elan users at Llacan) use multiple signs. At some point, I downloaded Bruno’s version, but now, when I correct the annotations, I re-introduce multiple signs for diacritics, which creates multiple versions for each form…  Maybe the diacritics should be unified before parsing (the way Bruno does for publication) if we want to improve its performance. It’s just a guess… Or, maybe there is a way to tell the parser to leave the lemmas  unchanged.  I will check again once I have finished the manual correction of the 4th sample.   But it’s taking me a long time as I am revising my transcription which was altered (oversimplified)  in the conversion from Elan.  B.  Bernard Caron57, avenue d’Italie75013 PARIS06 63 68 15 19 De : Kirian GuillerEnvoyé le :lundi 20 février 2023 22:22À : Arborator/arborator-frontendCc : B-CARON; MentionObjet :Re: [Arborator/arborator-frontend] Parser issue: timeout (Issue #181) Hello @B-CARON . We improved and made more stable the pipeline (especially for the kirparser). We now have no problem parsing your corpus (CONV-1 to 3 for training and the rest for parsing). I've just run a parsing with 30 epochs (less than 10mn) and I got the following results :{"UPOS":{"precision":0.9035667107001321,"recall":0.9035667107001321,"f1":0.9035667107001321},"XPOS":{"precision":1,"recall":1,"f1":1},"UFeats":{"precision":0.8665785997357992,"recall":0.8665785997357992,"f1":0.8665785997357992},"Lemmas":{"precision":0.8705416116248349,"recall":0.8705416116248349,"f1":0.8705416116248349},"UAS":{"precision":0.7582562747688243,"recall":0.7582562747688243,"f1":0.7582562747688243},"LAS":{"precision":0.6842800528401585,"recall":0.6842800528401585,"f1":0.6842800528401585}}I'm running another one with many more epochs to see how much we can reach for LAS.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by B-CARON** [comment]
Hi Kirian I have finished editing the 4th sample, and tried to run the parser (Kirparser). It crashed right at the beginning with  « status code error 500 »Do you have an idea why ?  B.  Bernard Caron57, avenue d’Italie75013 PARIS06 63 68 15 19 De : Kirian GuillerEnvoyé le :lundi 20 février 2023 22:22À : Arborator/arborator-frontendCc : B-CARON; MentionObjet :Re: [Arborator/arborator-frontend] Parser issue: timeout (Issue #181) Hello @B-CARON . We improved and made more stable the pipeline (especially for the kirparser). We now have no problem parsing your corpus (CONV-1 to 3 for training and the rest for parsing). I've just run a parsing with 30 epochs (less than 10mn) and I got the following results :{"UPOS":{"precision":0.9035667107001321,"recall":0.9035667107001321,"f1":0.9035667107001321},"XPOS":{"precision":1,"recall":1,"f1":1},"UFeats":{"precision":0.8665785997357992,"recall":0.8665785997357992,"f1":0.8665785997357992},"Lemmas":{"precision":0.8705416116248349,"recall":0.8705416116248349,"f1":0.8705416116248349},"UAS":{"precision":0.7582562747688243,"recall":0.7582562747688243,"f1":0.7582562747688243},"LAS":{"precision":0.6842800528401585,"recall":0.6842800528401585,"f1":0.6842800528401585}}I'm running another one with many more epochs to see how much we can reach for LAS.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by B-CARON** [comment]
Hi Ziqian I wonder if you could help me again with the Arborator parsing tool. I didn’t have any problem with the kirparser, but it suddenly stopped working for me, without even starting, with the error message (request failed with status code 500) I can’t find any problem in the annotation (it passed the Grew-match validation). See below a snapshot of my project  Thanks if you can spare some time for me ! Bernard Caron57, avenue d’Italie75013 PARIS06 63 68 15 19 De : Ziqian PengEnvoyé le :jeudi 26 janvier 2023 01:35À : Arborator/arborator-frontendCc : B-CARON; MentionObjet :Re: [Arborator/arborator-frontend] Parser issue: timeout (Issue #181) Hello,Thanks a lot for your feedback!It seems that the message begins with"<!--/* Font Definitions ***@***.***{font-family:"Cambria Math";"is not a bug report, can we know where you copied that?After checking the log file of parser backend, it seems that trankit is failed to train tokenizer required in its pipeline, we didn't know the reason yet and we'll look at it further...hopsparser and udify succeeded in training a model but failed to parse.For hopsparser, it seems that it makes use of the HEAD and DEPREL columns in files to parse, and it throws UDError if there's no root. Can you give a root to the sentences:# sent_id = SAY_BC_INT_01_Religion_286-286 and # sent_id = SAY_BC_INT_01_Religion_239-241in SAY_NC_INT_01_religion.conllu, then train with the 3 gold files and parse only this file after modification? I hope this works. We'll update the djangoBootparser to fix this problem soon.Udify threw another error during parsing we are trying to fix it.We'll try to make the popup message appears longer. In some cases, for example, if there's no unique root or there's underscore in HEAD in files to train (that didn't occur in the 3 training files of Zaar_Parsing_Tests), you may get a (currently very draft) error report and the relevant conll sentences will be removed.Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ziqianPeng** [comment]
Bonjour, 

Je suis désolée pour le bug et merci beaucoup pour votre feedback! 
J'ai l'impression que c'est à cause d'un typo lorsqu'on voulait ajouter une fonction: 
Dans backend il demande la valeur de "keep_pos", mais dans frontend le nom de cette valeur est "keep_upos" dans le backend-api.py 

peut-être @Kim ou @Kirian pourrait en corriger et relancer le backend grew pour voir? 

J'espère que le problème sera bientôt fixé et on vous tiens au courant. 

Ziqian Peng 



De: "B-CARON" ***@***.***> 
À: "Arborator" ***@***.***> 
Cc: "Ziqian Peng" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Mardi 28 Février 2023 22:46:42 
Objet: Re: [Arborator/arborator-frontend] Parser issue: timeout (Issue #181) 



Hi Ziqian I wonder if you could help me again with the Arborator parsing tool. I didn’t have any problem with the kirparser, but it suddenly stopped working for me, without even starting, with the error message (request failed with status code 500) I can’t find any problem in the annotation (it passed the Grew-match validation). See below a snapshot of my project Thanks if you can spare some time for me ! Bernard Caron57, avenue d’Italie75013 PARIS06 63 68 15 19 De : Ziqian PengEnvoyé le :jeudi 26 janvier 2023 01:35À : Arborator/arborator-frontendCc : B-CARON; MentionObjet :Re: [Arborator/arborator-frontend] Parser issue: timeout (Issue #181) Hello,Thanks a lot for your feedback!It seems that the message begins with"<!--/* Font Definitions ***@***.***{font-family:"Cambria Math";"is not a bug report, can we know where you copied that?After checking the log file of parser backend, it seems that trankit is failed to train tokenizer required in its pipeline, we didn't know the reason yet and we'll look at it further...hopsparser and udify succeeded in training a model but failed to parse.For hopsparser, it seems that it makes use of the HEAD and DEPREL columns in files to parse, and it throws UDError if there's no root. Can you give a root to the sentences:# sent_id = SAY_BC_INT_01_Religion_286-286 and # sent_id = SAY_BC_INT_01_Religion_239-241in SAY_NC_INT_01_religion.conllu, then train with the 3 gold files and parse only this file after modification? I hope this works. We'll update the djangoBootparser to fix this problem soon.Udify threw another error during parsing we are trying to fix it.We'll try to make the popup message appears longer. In some cases, for example, if there's no unique root or there's underscore in HEAD in files to train (that didn't occur in the 3 training files of Zaar_Parsing_Tests), you may get a (currently very draft) error report and the relevant conll sentences will be removed.Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by B-CARON** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 70.85pt 70.85pt 70.85pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by ziqianPeng** [comment]
Bonjour 
Pas de soucis, il semble que le problème est fixé? Merci à Kirian et Kim. 
est-ce que vous pouvez re-essayer ? 

Bonne journée, 

Ziqian Peng 


De: "B-CARON" ***@***.***> 
À: "Arborator" ***@***.***> 
Cc: "Ziqian Peng" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Mercredi 1 Mars 2023 12:43:44 
Objet: Re: [Arborator/arborator-frontend] Parser issue: timeout (Issue #181) 



<!-- 
/* Font Definitions */ 
@font-face 
{font-family:"Cambria Math"; 
panose-1:2 4 5 3 5 4 6 3 2 4;} 
@font-face 
{font-family:Calibri; 
panose-1:2 15 5 2 2 2 4 3 2 4;} 
/* Style Definitions */ 
p.MsoNormal, li.MsoNormal, div.MsoNormal 
{margin:0cm; 
font-size:11.0pt; 
font-family:"Calibri",sans-serif;} 
a:link, span.MsoHyperlink 
{mso-style-priority:99; 
color:blue; 
text-decoration:underline;} 
.MsoChpDefault 
{mso-style-type:export-only;} 
@page WordSection1 
{size:612.0pt 792.0pt; 
margin:70.85pt 70.85pt 70.85pt 70.85pt;} 
div.WordSection1 
{page:WordSection1;}

**Comment by B-CARON** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 70.85pt 70.85pt 70.85pt;}
div.WordSection1
	{page:WordSection1;}
