### ISSUE TITLE
Can't login and access the treebank

### ISSUE THREAD

**Issue by NeldaKote** [Arborator/arborator-frontend#209]
Hello, 

Is there any problem with the online platform today? I attempted to log in but can't and the error "504 Gateway Time-out" appears. Also, my colleagues attempted to access the platform today but they faces with same errors, like "error 502" and couldn't save the changes on the sentence she was working on, or "no data available" and couldn't access the treebank.

Thank you in advance, 

Nelda

**Comment by khansadaoudi** [comment]
Hello, 

Thank you for reporting this issue we will fix it asap.

**Comment by kimgerdes** [comment]
it's back up. please check if all is working as expected.

**Comment by khansadaoudi** [comment]
ArboratorGrew is working now

**Comment by B-CARON** [comment]
I’m sorry, but the parser tool still isn’t working. Bernard Caron57, avenue d’Italie75013 PARIS06 63 68 15 19 De : khansadaoudiEnvoyé le :jeudi 23 mars 2023 10:06À : Arborator/arborator-frontendCc : SubscribedObjet :Re: [Arborator/arborator-frontend] Can't login and access the treebank (Issue #209) ArboratorGrew is working now—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
