### ISSUE TITLE
How to split tokens in the annotation view?

### ISSUE THREAD

**Issue by Lguyogiro** [Arborator/arborator-frontend#238]
I'm new to arborator, and I can't figure out how to create multi-word tokens (MWTs) in the annotation interface. For example, if I have a sentence with a word that needs to be split into a multi-word token, how can I do this?

Thanks.

**Comment by B-CARON** [comment]
In the REF line of your sentence in Arborator, select precisely the word you want to split. (NB : It will not work if you include the surrounding spaces. Do not double click. It won’t work either.) :   This will open the  Following menu :     Click on « Split token » :         That’s it.  Bernard Caron  De : Robert PughEnvoyé le :samedi 1 juillet 2023 02:23À : Arborator/arborator-frontendCc : SubscribedObjet :[Arborator/arborator-frontend] How to split tokens in the annotation view? (Issue #238) I'm new to arborator, and I can't figure out how to create multi-word tokens (MWTs) in the annotation interface. For example, if I have a sentence with a word that needs to be split into a multi-word token, how can I do this?Thanks.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by bguil** [comment]
To complete @B-CARON's answer:

 - When a sentence editor is open, highlight the word you want to split (_good_ in the screenshot)

<img width="862" alt="Screenshot 2023-07-01 at 14 43 42" src="https://github.com/Arborator/arborator-frontend/assets/687155/118c2bae-c56f-47b0-81ec-3adfc81adf13">

 - In the modal menu select `split token` and you can split it in two subpart (_go_ and _od_ in the example)

<img width="844" alt="Screenshot 2023-07-01 at 14 47 00" src="https://github.com/Arborator/arborator-frontend/assets/687155/1330667d-e722-4422-b370-3f80d33864e8">

 - the old token _good_ is split in two token _go_ and _od_. But the multi-word token is not added (unfortunately) by ArboratorGrew. See the correspondig Conllu:

<img width="567" alt="Screenshot 2023-07-01 at 14 49 24" src="https://github.com/Arborator/arborator-frontend/assets/687155/332fd093-cecb-49c1-8fa8-edb483693e20">

 - The MWT line `6-7	…` should be added manually in the Conllu file (see next screenshot).

<img width="584" alt="Screenshot 2023-07-01 at 14 52 25" src="https://github.com/Arborator/arborator-frontend/assets/687155/54301817-d500-4c30-a017-bcb602945c77">

**Comment by bguil** [comment]
@khansadaoudi: we should add a checkbox option in the "split token" window to decide if we want to add a multi-word token (see previous message).

**Comment by Lguyogiro** [comment]
Awesome, thank you!

I agree that it would be great if there was a way to choose "Split into MWT", and represent the MWTs in the graph by, e.g., highlighting them in the same color or underlining them or something.

**Comment by Lguyogiro** [comment]
Maybe I should leave this open then, if it has turned into a feature request.

**Comment by khansadaoudi** [comment]
We added this option in the last commit
