### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by Lguyogiro** [Arborator/arborator-frontend#240]
Currently, English and French are supported as languages for the user interface. How can I add support for an additional language?

**Comment by khansadaoudi** [comment]
@Lguyogiro In ArboratorGrew, we are using VueJs pluging [Vue I18n](https://vue-i18n.intlify.dev/) that helps us to integrate the internationalization feature. 
In order to add a new language, I suggest you to create a pull request where you need to follow this steps:

1. Create folder in **arborator-frontend/src/i18n** for the new supported language.
2. Create `index.ts`  translation file.
3. Add the new language translation in key-value format, using the same keys as those used in the FR and EN translation files. Exmple from  `en-us\index.ts` , `fr-fra\index.ts` files: 
En: ` failed: 'Action failed' ` 
Fr: `failed: "L'action a échoué"`
Like you see we have the same key in the two files for two different values.
4. Import your transaltion file in `/i18n/index.ts`.

Once your translation is ready we will manage to integrate in user interface. Thank you for your proposition.
Have a good day.
