### ISSUE TITLE
What determines which dependency labels are available in the relation table?

### ISSUE THREAD

**Issue by mr-martian** [Arborator/arborator-frontend#243]
I really like the relation table feature, but I can't always figure out why it shows me the options that it does.

Here I went through the 3 instances of `flat` and found that all of them were errors, and afterwards, I can't click on `flat`, which makes sense, but then I also can't click on `nmod`, which is strange since the query `pattern { GOV -[nmod]-> DEP }` gives 635 results.
![image](https://github.com/Arborator/arborator-frontend/assets/5350777/1be079b5-856c-4cf3-9e66-7ba7514f3362)

And also `case` and `nmod:poss` are missing from the list.

**Comment by bguil** [comment]
@khansadaoudi: I think that the problem is in the frontend.
I've checked the response of the backend server. It seems to be correct.
For instance, on the [SUD_English-PUD](https://arboratorgrew.elizia.net/#/projects/SUD_English_PUD), the service `relationTables` returns the joined file [rt.json](https://github.com/Arborator/arborator-frontend/files/11972131/rt.json.txt).

which contains:

```
…
    "comp:aux@pass": { "AUX": { "VERB": 272, "ADP": 1, "ADJ": 1 } },
    "comp:aux": { "AUX": { "VERB": 307, "PRON": 1, "AUX": 101, "ADJ": 1 } },
…
```

but the interface does not make `comp:aux` clikable and does not show `comp:aux@pass` at all:

<img width="465" alt="Screenshot 2023-07-06 at 22 43 41" src="https://github.com/Arborator/arborator-frontend/assets/687155/14641f00-7ad4-4ee8-a114-c7d0fe994216">

**Comment by khansadaoudi** [comment]
@bguil yes I have tested this in  the afternoon and I think the problem concerns the frontend 
I will fix it soon
