### ISSUE TITLE
cache problem when opening new sample

### ISSUE THREAD

**Issue by khansadaoudi** [Arborator/arborator-frontend#252]
Cache problem when I open new sample the data of the previous opened sample is displayed. like the screenshot I'm in chinese sample and it's loading paris sotries sample 
![image](https://github.com/Arborator/arborator-frontend/assets/50585493/83cceab0-c70f-4f23-ae8f-786053a61f97)

**Comment by khansadaoudi** [comment]
fixed in [this commit](https://github.com/Arborator/arborator-frontend/commit/86e6a25320a202a8c0e24b623a594da25529d5c1)

**Comment by kirianguiller** [comment]
actually, I also thought this commit fixed the cache problem, but it didnt. The problem was not related to the fact that sentences were not frozen, but by the fact that the virtual scroller had no constrain on the height, which made it expand for the totallity of its items (sentences). So instead of having only a few tens of sentences in the scroller, the totality was loaded in memory.

This was the commit that fixed this performance issue : https://github.com/Arborator/arborator-frontend/commit/774e9d1264cdcef10257d21e3cb1ab4285a61ae5

**Comment by kirianguiller** [comment]
sorry, I misinterpreted the issue. Do you still have this issue ? I can't reproduce it.
