### ISSUE TITLE
[Bug]: Labels change from one user to another

### ISSUE THREAD

**Issue by s-herrera** [Arborator/arborator-frontend#311]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some users (students) of my annotation project have different labels than those specify by the project, even if I'm the only admin of the project and they cannot change them.

These are the available UPOS labels: 

![image](https://github.com/Arborator/arborator-frontend/assets/95502001/24509343-ac6e-493a-ad7e-23c99a42bbd1)

These are the ones available for one of the users:

![image](https://github.com/Arborator/arborator-frontend/assets/95502001/e1edebad-a94f-4cd6-aaa4-0c611e21cca7)

It seems that the label ADV is for him "AVANCÉ" and the label NUM is "NUMÉRO".

The annotation settings are ok:

![image](https://github.com/Arborator/arborator-frontend/assets/95502001/c456cbc4-59d2-489b-8704-72995620f58c)

It's possible to add a new UPOS label. In this case, the new label will appear, but the wrong labels will be still there. 

### Steps To Reproduce

It's difficult to know how to reproduce this bug.

### Project name

 L2_Syntaxe_et_Morphologie1

**Comment by khansadaoudi** [comment]
@s-herrera I know what is the problem your student activate the google traduction so it translates the label of the upos dialog. Because, first I couldn't reproduce the issue and then I found that the label of the button is not the same in your screen it's written OK and in their screen is D'accord
I tried to translate the page and I found out that the problem is there so just ask them to use default language of the browser.
![Capture d’écran du 2023-12-14 13-27-46](https://github.com/Arborator/arborator-frontend/assets/50585493/1f011cb4-d446-45d3-874c-10351d22c476)
![Capture d’écran du 2023-12-14 13-27-58](https://github.com/Arborator/arborator-frontend/assets/50585493/44b30397-28e6-4da0-9e39-74fcd6e6e6ad)

**Comment by s-herrera** [comment]
Amazing! Thank you so much.
