### ISSUE TITLE
[Bug]: Segmentation not possible for annotators

### ISSUE THREAD

**Issue by vistamou** [Arborator/arborator-frontend#346]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

The segmentation options are not available for annotators or validators, 
are only available for administrators and owners of the projects. Could
you please enable them? otherwise all annotator to be able to edit the incorrect segmentation 
of a sentence should be changed to administrators, which is not very reasonable.

### Steps To Reproduce

1. Open a sentence, select a token, and try to segment being an **annotator** of a project.

### What browsers are you seeing the problem on?

Chrome

**Comment by khansadaoudi** [comment]
Changing the sentences segmentation by annotators will change the structure of the whole corpus. In ArboratorGrew all the users must have the same sentences, so if we allow all the users to change the segementation of the sentences we will lose the coherence of the sample. Because of that the  feature is available only of the admin of the project. In order to avoid asking the admin to change the segementation every time ask them for upgrading your access rights

**Comment by vistamou** [comment]
I understand that, but segmentation might be wrong, due to wrong way ot tokenizing the corpus, so in such cases 
what do you do? as you say you should ask the admin to change the segmentation, which is not optmimum solution in a big corpus, since you might have thousand of errors--

so can you explain what do you mean by the 2nd option you refer '...ask them for upgrading your access rights' ??
 you mean to give admin access to all annotators?

**Comment by khansadaoudi** [comment]
Yes, that's what I mean, because the features related to the structure of the project such as sentence segmentation are reserved to the admins
