### ISSUE TITLE
[Feature request]: Training from a pretrain model

### ISSUE THREAD

**Issue by RZiane** [Arborator/arborator-frontend#361]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

Hi Khensa, 
Before your intervention on the frontend for the parser, we could select an existing trained model from the list and continue to train with new sentences in another collection.
Do you think it would be possible to revert to this feature?

**Comment by B-CARON** [comment]
Yes, please. Useful to use a pre-existing model for dialects or languages from a same family.   Bernard CARON57, avenue d’Italie75013 PARIS06 63 68 15 19 De : RZianeEnvoyé le :jeudi 14 mars 2024 16:38À : Arborator/arborator-frontendCc : SubscribedObjet :[Arborator/arborator-frontend] [Feature request]: Training from a pretrain model (Issue #361) Is there already a feature request for this?[X] I have searched the existing issuesDescribe the problem to be solvedHi Khensa,Before your intervention on the frontend for the parser, we could select an existing trained model from the list and continue to train with new sentences in another collection.Do you think it would be possible to revert to this feature?Suggest a solutionNo response—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
