### ISSUE TITLE
Cannot upload conllu file from UDpipe

### ISSUE THREAD

**Issue by adripag** [Arborator/arborator-frontend#373]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I try to upload a file output from UDpipe [https://lindat.mff.cuni.cz/services/udpipe/], I get a message: <name of file> contains sentence with empty metadata value.

### Steps To Reproduce

Open UDPipe-  https://lindat.mff.cuni.cz/services/udpipe/
Default selection Udpipe 2.12
Select Language model (Portuguese-bosque)
Type sentence
Process
Save output file
Upload output file in Arborator

### Project name

Ling computacional

### Anything else?

<img width="1267" alt="image" src="https://github.com/Arborator/arborator-frontend/assets/80424602/a7f089d1-711a-4e57-be66-42ccd915dc0a">

### What browsers are you seeing the problem on?

Chrome

**Comment by khansadaoudi** [comment]
Hello,that's not a bug you have a problem in your data that you tried to upload.  I have used Udpipe parser and I got generated metadata keys with empty values like the exemple below 
```   
    # generator = UDPipe 2, https://lindat.mff.cuni.cz/services/udpipe
    # udpipe_model = portuguese-bosque-ud-2.12-230717
    # udpipe_model_licence = CC BY-NC-SA
    # newdoc
    # newpar
    # sent_id = 1
```
`# newdoc ` and `# newpar`  keys don't have a value. Try to remove this empty keys or add values to them in order to solve this problem.
